name: "HCL AppScan CodeSweep"
on: [pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
        with:
          asoc_key:{2e8aef7d-52ac-b69f-1235-6499fb05c2ac}
          asoc_secret:{9I/smrhwVTAQqF9WURC7kIMGjpLBKsVsD4eTl6B592A=}
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}